import { type Project, projects } from './projects';
import { type User, users } from './users';

function filterDefined<T>(arr: (T | undefined)[]): T[] {
  return arr.filter((item): item is T => item !== undefined);
}

export interface Team {
  id: string;
  name: string;
  icon: string;
  joined: boolean;
  color: string;
  members: User[];
  projects: Project[];
}

export const teams: Team[] = [
  {
    id: 'CORE',
    name: 'LNDevコアチーム',
    icon: '🛠️',
    joined: true,
    color: '#FF0000',
    members: filterDefined([users[8], users[10], users[2], users[3], users[4]]),
    projects: filterDefined([projects[5], projects[8], projects[3]]),
  },
  {
    id: 'DESIGN',
    name: 'デザインシステム',
    icon: '🎨',
    joined: true,
    color: '#00FF00',
    members: filterDefined([users[7], users[3]]),
    projects: filterDefined([
      projects[1],
      projects[1],
      projects[2],
      projects[3],
    ]),
  },
  {
    id: 'PERF',
    name: 'パフォーマンスラボ',
    icon: '☀️',
    joined: false,
    color: '#0000FF',
    members: filterDefined([
      users[5],
      users[0],
      users[1],
      users[2],
      users[3],
      users[4],
      users[6],
    ]),
    projects: filterDefined([projects[8], projects[8]]),
  },
  {
    id: 'UX',
    name: 'UXチーム',
    icon: '👨🏼‍🎨',
    joined: false,
    color: '#FF00FF',
    members: filterDefined([users[3]]),
    projects: filterDefined([
      projects[1],
      projects[1],
      projects[2],
      projects[3],
    ]),
  },
  {
    id: 'DATA',
    name: 'データサイエンス',
    icon: '📊',
    joined: false,
    color: '#0000FF',
    members: filterDefined([users[8], users[9], users[10]]),
    projects: filterDefined([projects[4]]),
  },
  {
    id: 'MOBILE',
    name: 'モバイル開発',
    icon: '📱',
    joined: false,
    color: '#0000FF',
    members: [],
    projects: [],
  },
  {
    id: 'WEB',
    name: 'ウェブ開発',
    icon: '🌐',
    joined: true,
    color: '#0000FF',
    members: filterDefined([users[8], users[9], users[10], users[11]]),
    projects: filterDefined([projects[1], projects[2]]),
  },
  {
    id: 'UI',
    name: 'UIチーム',
    icon: '👨🏼‍🎨',
    joined: false,
    color: '#FF00FF',
    members: filterDefined([
      users[6],
      users[7],
      users[2],
      users[3],
      users[4],
      users[5],
    ]),
    projects: filterDefined([projects[1], projects[0], projects[2]]),
  },
  {
    id: 'CLOUD',
    name: 'クラウドインフラ',
    icon: '☁️',
    joined: false,
    color: '#4A90E2',
    members: filterDefined([users[1], users[5], users[11], users[9]]),
    projects: filterDefined([projects[6], projects[7]]),
  },
  {
    id: 'SECURITY',
    name: 'セキュリティチーム',
    icon: '🔒',
    joined: false,
    color: '#2E2E2E',
    members: filterDefined([users[4], users[8], users[11]]),
    projects: filterDefined([projects[0], projects[5], projects[8]]),
  },
  {
    id: 'AI',
    name: 'AI研究',
    icon: '🧠',
    joined: true,
    color: '#9B59B6',
    members: filterDefined([users[2], users[10], users[7], users[5]]),
    projects: filterDefined([projects[4], projects[8]]),
  },
  {
    id: 'QA',
    name: '品質保証',
    icon: '✅',
    joined: false,
    color: '#F1C40F',
    members: filterDefined([users[3], users[6], users[1]]),
    projects: filterDefined([projects[2], projects[3], projects[7]]),
  },
  {
    id: 'DEVOPS',
    name: 'DevOps',
    icon: '⚙️',
    joined: false,
    color: '#E67E22',
    members: filterDefined([users[0], users[4], users[9]]),
    projects: filterDefined([projects[5], projects[6]]),
  },
  {
    id: 'FRONTEND',
    name: 'フロントエンド専門家',
    icon: '🖥️',
    joined: false,
    color: '#1ABC9C',
    members: filterDefined([users[7], users[3], users[11], users[2]]),
    projects: filterDefined([projects[1], projects[2]]),
  },
  {
    id: 'BACKEND',
    name: 'バックエンドエンジニア',
    icon: '🗄️',
    joined: false,
    color: '#34495E',
    members: filterDefined([users[0], users[8], users[10]]),
    projects: filterDefined([projects[0], projects[5], projects[8]]),
  },
  {
    id: 'PRODUCT',
    name: 'プロダクト',
    icon: '📋',
    joined: false,
    color: '#C0392B',
    members: filterDefined([users[1], users[6], users[9]]),
    projects: filterDefined([projects[3], projects[4]]),
  },
  {
    id: 'ANALYTICS',
    name: '分析チーム',
    icon: '📈',
    joined: false,
    color: '#7F8C8D',
    members: filterDefined([users[5], users[10], users[8]]),
    projects: filterDefined([projects[4], projects[7]]),
  },
  {
    id: 'INNO',
    name: 'イノベーションラボ',
    icon: '💡',
    joined: false,
    color: '#F39C12',
    members: filterDefined([users[2], users[7], users[11], users[4]]),
    projects: filterDefined([projects[8], projects[8]]),
  },
  {
    id: 'API',
    name: 'API開発',
    icon: '🔌',
    joined: false,
    color: '#16A085',
    members: filterDefined([users[0], users[8], users[10], users[4]]),
    projects: filterDefined([projects[0], projects[5]]),
  },
  {
    id: 'UXR',
    name: 'UXリサーチ',
    icon: '🔍',
    joined: false,
    color: '#8E44AD',
    members: filterDefined([users[3], users[6], users[9], users[7]]),
    projects: filterDefined([projects[1], projects[3], projects[4]]),
  },
];
