/**
 * Generate a SQL seed file for Cloudflare D1 from the mock reference data
 * (statuses, priorities, labels, teams, projects, team_projects).
 *
 *   bun run seed:d1:sql      # write drizzle/seed.sql
 *   bun run seed:d1          # write + apply to local D1
 *   bun run seed:d1:remote   # write + apply to remote D1
 *
 * User accounts are NOT seeded — they are created by Better Auth on first
 * Google sign-in, and new users are auto-added to the CORE team.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { labels } from '../mock-data/labels';
import { priorities } from '../mock-data/priorities';
import { projects } from '../mock-data/projects';
import { status } from '../mock-data/status';
import { teams } from '../mock-data/teams';

function sqlValue(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

function insert(
  table: string,
  columns: string[],
  rows: Array<Array<string | number | null | undefined>>,
  conflict: 'REPLACE' | 'IGNORE' = 'REPLACE'
): string {
  if (rows.length === 0) return '';
  const values = rows
    .map((row) => `  (${row.map(sqlValue).join(', ')})`)
    .join(',\n');
  return `INSERT OR ${conflict} INTO ${table} (${columns.join(
    ', '
  )}) VALUES\n${values};\n`;
}

function build(): string {
  const parts: string[] = ['-- Generated by scripts/seed-d1.ts\n'];

  parts.push(
    insert(
      'statuses',
      ['id', 'slug', 'name', 'color', 'icon', 'display_order'],
      status.map((s, i) => [s.id, s.id, s.name, s.color, s.id, i])
    )
  );

  parts.push(
    insert(
      'priorities',
      ['id', 'slug', 'name', 'icon', 'display_order'],
      priorities.map((p, i) => [p.id, p.id, p.name, p.id, i])
    )
  );

  parts.push(
    insert(
      'labels',
      ['id', 'slug', 'name', 'color'],
      labels.map((l) => [l.id, l.id, l.name, l.color])
    )
  );

  parts.push(
    insert(
      'teams',
      ['id', 'slug', 'name', 'icon', 'color'],
      teams.map((t) => [
        t.id,
        t.id,
        t.name,
        typeof t.icon === 'string' ? t.icon : null,
        t.color ?? null,
      ])
    )
  );

  parts.push(
    insert(
      'projects',
      ['id', 'name', 'icon', 'percent_complete', 'status_id'],
      projects.map((p) => [
        p.id,
        p.name,
        typeof p.icon === 'string' ? p.icon : 'folder',
        p.percentComplete ?? 0,
        p.status?.id ?? null,
      ])
    )
  );

  const teamProjectRows = teams.flatMap((team) =>
    team.projects.map((project) => [
      `${team.id}_${project.id}`,
      team.id,
      project.id,
    ])
  );
  parts.push(
    insert(
      'team_projects',
      ['id', 'team_id', 'project_id'],
      teamProjectRows,
      'IGNORE'
    )
  );

  return parts.filter(Boolean).join('\n');
}

const outPath = resolve(import.meta.dirname, '../drizzle/seed.sql');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, build());
console.log(`Wrote seed SQL to ${outPath}`);
